name: Python Tests

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use a Ubuntu runner for the workflow

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout your repository code

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # You can set the Python version here
        
    - name: Upgrade pip and setuptools
      run: python -m pip install --upgrade pip setuptools
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install your dependencies

    - name: Run tests
      run: |
        pytest  # Run pytest to execute tests
